name: Docker Validation

on:
  push:
    branches:
      - Dev2
  pull_request:
    branches:
      - Dev2

jobs:
  validate-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for backend
        run: docker build -t backend-test -f ./backend/Dockerfile ./backend
        working-directory: . # Set working directory to root where docker-compose.yml is

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run Docker Compose services
        run: docker-compose -f docker-compose.yml up -d --build
        working-directory: . # Set working directory to root

      - name: Check Docker Compose services status
        run: docker-compose -f docker-compose.yml ps
        working-directory: .

      - name: Stop Docker Compose services
        if: always() # Ensure services are stopped even if previous steps fail
        run: docker-compose -f docker-compose.yml down
        working-directory: .

